# Generated by Django 6.0 on 2025-12-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
