# Generated by Django 6.0 on 2025-12-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoicepart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='labour_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='parts_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
