# Generated by Django 6.0 on 2025-12-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bike_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='work_photo',
            field=models.ImageField(blank=True, null=True, upload_to='work_photos/'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20),
        ),
    ]
