# Generated by Django 6.0 on 2025-12-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicerequest_work_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='problem_description',
            field=models.TextField(blank=True),
        ),
    ]
