# Generated by Django 6.0 on 2025-12-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_servicerequest_problem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='labour_charge',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=8),
        ),
    ]
