# Generated by Django 6.0 on 2026-01-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_emailnotification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailnotification',
            name='sent_at',
        ),
    ]
