# Generated by Django 5.0.1 on 2026-03-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField(verbose_name='What Enquiry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
