# Generated by Django 6.0 on 2025-12-14 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicerequest_work_photo_and_more'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField()),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicerequest')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.sparepart')),
            ],
        ),
    ]
