# Generated by Django 6.0 on 2025-12-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_servicepartusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
