# Generated by Django 6.0 on 2025-12-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_servicerequest_status'),
        ('parts', '0003_alter_sparepart_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepartusage',
            name='price_per_piece',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicepartusage',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='core.servicerequest'),
        ),
    ]
