# Generated by Django 6.0 on 2025-12-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_servicepartusage_price_per_piece_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepartusage',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicepartusage',
            name='price_per_piece',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
