# Generated by Django 6.0 on 2025-12-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_servicepartusage_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepartusage',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
