# Generated by Django 6.0 on 2026-01-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_alter_servicepartusage_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepartusage',
            name='price_per_piece',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
