# Generated by Django 6.0 on 2025-12-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Monthly Attendance Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
