# Generated by Django 6.0 on 2025-12-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_monthlyattendancereport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyReport',
            new_name='MonthlyRevenueReport',
        ),
        migrations.AlterModelOptions(
            name='monthlyattendancereport',
            options={'verbose_name': 'Monthly Attendance Report', 'verbose_name_plural': 'Attendance Reports'},
        ),
        migrations.AlterModelOptions(
            name='monthlyrevenuereport',
            options={'verbose_name': 'Monthly Revenue Report', 'verbose_name_plural': 'Revenue Reports'},
        ),
    ]
