# Generated by Django 6.0 on 2025-12-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Attendance Report',
                'verbose_name_plural': 'Attendance Reports',
                'managed': False,
            },
        ),
    ]
